### ISSUE TITLE
improvement: need to use different configuration file

### ISSUE THREAD

**Issue by ravi005e** [mlucascardoso/dotenv-json-complex#1]
Can you please improvement it:?

I want to do the following:
I have multile environment file
.env.local.json
.env.qa.json
.env.prod.json
.env.dev.json

now I want to export at terminal:
export NODE_ENV=.env.qa.json

other than that, it works fine

Thanks

**Comment by mlucascardoso** [comment]
Hi ravi005e!

You already can do that. Sorry, the README has a lack of information.

So, to achieve what you want just do the following:

require('dotenv-json-complex')({ environment: 'qa' });

This will look for .env.qa.json file and load it in memory.

Please let me know if it worked for you.
